# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: python:3.8
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python -V
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
stages:
- build
- lint
- test
- staging
- deploy
- review
- dast
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
build:
  stage: build
  script:
  - source venv/bin/activate
  - pip install -r requirements.txt
  - python manage.py migrate
flake8:
  stage: lint
  script:
  - source venv/bin/activate
  - flake8 --max-line-length=150 --ignore=E266,E501,E712,F811 *.py
pytest:
  stage: test
  script:
  - source venv/bin/activate
  - python manage.py test --settings=jobs.settings -v3
newman_tests:
  stage: test
  before_script:
  - ''
  image:
    name: postman/newman_alpine33
    entrypoint:
    - ''
  script:
  - newman --version
  - newman run ./tests/LYIT-JOB-PORTAL.postman_collection.json -e ./tests/LYIT-JOB-PORTAL.postman_collection.json
staging:
  stage: staging
  script:
  - apt update -y
  - apt install -y ruby-dev git
  - gem install dpl
  - dpl --provider=heroku --app=lyit-job-portal-staging --api-key=$heroku_api_key
    --skip-cleanup
deploy:
  stage: deploy
  script:
  - apt update -y
  - apt install -y ruby-dev git
  - gem install dpl
  - dpl --provider=heroku --app=lyit-job-portal --api-key=$heroku_api_key --skip-cleanup
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
